/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export declare namespace IRapiDrive {
  export type DriverStruct = {
    driver: string;
    trips: BigNumberish;
    inSystem: boolean;
    timeIn: BigNumberish;
    awarded: boolean;
  };

  export type DriverStructOutput = [
    string,
    number,
    boolean,
    BigNumber,
    boolean
  ] & {
    driver: string;
    trips: number;
    inSystem: boolean;
    timeIn: BigNumber;
    awarded: boolean;
  };
}

export interface IRapiDriveInterface extends utils.Interface {
  contractName: "IRapiDrive";
  functions: {
    "getDriver(address)": FunctionFragment;
    "resetTrip()": FunctionFragment;
    "tollEntry(string)": FunctionFragment;
    "tollExit(string)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "getDriver", values: [string]): string;
  encodeFunctionData(functionFragment: "resetTrip", values?: undefined): string;
  encodeFunctionData(functionFragment: "tollEntry", values: [string]): string;
  encodeFunctionData(functionFragment: "tollExit", values: [string]): string;

  decodeFunctionResult(functionFragment: "getDriver", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "resetTrip", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tollEntry", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tollExit", data: BytesLike): Result;

  events: {
    "offRampExitedTollPaid(bytes32,uint256,string,uint256)": EventFragment;
    "onRampEntered(bytes32,uint256,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "offRampExitedTollPaid"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "onRampEntered"): EventFragment;
}

export type offRampExitedTollPaidEvent = TypedEvent<
  [string, BigNumber, string, BigNumber],
  {
    hashedDriver: string;
    timeExited: BigNumber;
    tollIdentifier: string;
    tollCost: BigNumber;
  }
>;

export type offRampExitedTollPaidEventFilter =
  TypedEventFilter<offRampExitedTollPaidEvent>;

export type onRampEnteredEvent = TypedEvent<
  [string, BigNumber, string],
  { hashedDriver: string; timeEntered: BigNumber; tollIdentifier: string }
>;

export type onRampEnteredEventFilter = TypedEventFilter<onRampEnteredEvent>;

export interface IRapiDrive extends BaseContract {
  contractName: "IRapiDrive";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IRapiDriveInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getDriver(
      drive: string,
      overrides?: CallOverrides
    ): Promise<[IRapiDrive.DriverStructOutput]>;

    resetTrip(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    tollEntry(
      tollIdentifier: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    tollExit(
      tollIdentifier: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  getDriver(
    drive: string,
    overrides?: CallOverrides
  ): Promise<IRapiDrive.DriverStructOutput>;

  resetTrip(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  tollEntry(
    tollIdentifier: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  tollExit(
    tollIdentifier: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getDriver(
      drive: string,
      overrides?: CallOverrides
    ): Promise<IRapiDrive.DriverStructOutput>;

    resetTrip(overrides?: CallOverrides): Promise<void>;

    tollEntry(tollIdentifier: string, overrides?: CallOverrides): Promise<void>;

    tollExit(tollIdentifier: string, overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "offRampExitedTollPaid(bytes32,uint256,string,uint256)"(
      hashedDriver?: null,
      timeExited?: null,
      tollIdentifier?: null,
      tollCost?: null
    ): offRampExitedTollPaidEventFilter;
    offRampExitedTollPaid(
      hashedDriver?: null,
      timeExited?: null,
      tollIdentifier?: null,
      tollCost?: null
    ): offRampExitedTollPaidEventFilter;

    "onRampEntered(bytes32,uint256,string)"(
      hashedDriver?: null,
      timeEntered?: null,
      tollIdentifier?: null
    ): onRampEnteredEventFilter;
    onRampEntered(
      hashedDriver?: null,
      timeEntered?: null,
      tollIdentifier?: null
    ): onRampEnteredEventFilter;
  };

  estimateGas: {
    getDriver(drive: string, overrides?: CallOverrides): Promise<BigNumber>;

    resetTrip(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    tollEntry(
      tollIdentifier: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    tollExit(
      tollIdentifier: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getDriver(
      drive: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    resetTrip(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    tollEntry(
      tollIdentifier: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    tollExit(
      tollIdentifier: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
